### ISSUE TITLE
Error When Trying To Generate Secrets With Terraform

### ISSUE THREAD

**Issue by EthanDavis** [secrethub/terraform-provider-secrethub#68]
Hi I keep getting this error when I try to create new secrets with terraform 
`Error: Repo not found (server.repo_not_found)`
I've been following the guide that is in the secrethub docs. Was wondering if someone could help me figure out what's going on? 

Here is my terraform 
provider "aws" {
  region = var.region
}

provider "secrethub" {
  credential = file("~/.secrethub/credential")
}

terraform {
  backend "s3" {
    bucket = "poc-terraformstate"
    key = "poc/tirgus-infrastructure/"
    region = "us-east-2"
  }
}

data "aws_caller_identity" "current" {}

locals {
  secrethub_dir = "tirgus-api/poc"
}

resource "secrethub_secret" "db_password" {
  path = "${local.secrethub_dir}/db/password"

  generate {
    length      = 22
  }
}

resource "secrethub_secret" "db_user" {
  path  = "${local.secrethub_dir}/db/user"
  value = "schema_user"
}

resource "aws_db_instance" "postgres_instance" {
  allocated_storage = 20
  storage_type = "gp2"
  engine = "postgres"
  engine_version = "9.6.3"
  instance_class = "db.t2.micro"
  name = "tirgusApiDb"
  identifier = "tirgus-api-db"
  username = secrethub_secret.db_user.value
  password =  secrethub_secret.db_password.value
  publicly_accessible = true
  final_snapshot_identifier = "tirgus-api-db-final-SNAPSHOT"
  parameter_group_name = "default.postgres9.6"

}

secrethub version 0.37.0, build 22adaf4
Terraform version 0.12.23

Sorry if this isn't the correct place to ask this question. I wasn't sure where I should ask though.

Thanks,
Ethan

**Comment by SimonBarendse** [comment]
Hi Ethan,

the secret resource creates the secret in the path is refers to, in your example `tirgus-api/poc/db/password` and `tirgus-api/poc/db/user`. It relies on the `tirgus-api/poc` repo and `tirgus-api/poc/db` directory to already exist.
We'll be adding resources for repositories and directories as well, so that you can manage those in Terraform. In the meantime, you can create them using the CLI with [`repo init`](https://secrethub.io/docs/reference/cli/repo/#init) and [`mkdir`](https://secrethub.io/docs/reference/cli/mkdir/).

Hope this helps :smile:

You can ask questions in our [community Discord](https://discordapp.com/invite/wcxV5RD) and via support@secrethub.io , but also feel free to ask more questions here :)
